name: money_manager
description: A Money Manager Flutter app
publish_to: "none" # Remove if you want to publish
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add firebase, google_sign_in etc later when integrating Firebase Auth
  # firebase_core: ^2.13.1
  # firebase_auth: ^4.6.4
  # cloud_firestore: ^4.6.3
  # google_sign_in: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/login_logo.png
    - assets/signup_logo.png
